### ISSUE TITLE
Crash when parsing `<summary>` tag

### ISSUE THREAD

**Issue by dkasak** [tree-sitter/tree-sitter-html#100]
This was encountered while using tree-sitter-html from within nvim, so I only know how to reproduce it from there. See https://github.com/nvim-treesitter/nvim-treesitter/issues/6665 for details.

**Comment by amaanq** [comment]
this isn't reproducible for me using a variety of platforms and compilers - you're gonna need to ensure a) you built the parser with HEAD, using an older version WILL crash due to changes in libtree-sitter and b) you're *loading* that parser from HEAD

**If** possible, a backtrace would be useful - if you're on Linux `coredumpctl` is your friend, and if you can, compile the parser manually with `-g` (use the makefile if you don't know how to compile it and tack on `CFLAGS='-g'`) and move this to your RTP
